### PR TITLE
add clearCookie

### PR DESCRIPTION
**Pull request by Whoaa512**

### CODE REVIEW

**Comment by nathschmidt** [comment]
Hey, thanks for submitting this, and including a test case.

My only problem is pulling in a dependancy to use just one function. Could you avoid adding the extra dependancy?

**Comment by Whoaa512** [comment]
The dependency is a single function. Would you prefer an inline solution to achieve the same effect?

**Comment by nathschmidt** [comment]
I would yeah.

Also, I'm not sure why you're overriding the `path` option? Seems to me that path shouldn't be relevant, only setting expires.

**Comment by Whoaa512** [comment]
Updated

**Comment by nathschmidt** [comment]
Cool, merged.

Thanks buddy!

**Comment by nathschmidt** [comment]
Updated and published.

**Pull request merged**
